[package]
name = "egui_mobius_macros"
version = "0.3.0-alpha.4"
edition = "2024"

[dependencies]
syn = { version = "2.0", features = ["derive", "parsing"] }
quote = "1.0"
proc-macro2 = "1.0"

[lib]
proc-macro = true
