#cargo-features = ["edition2024"]

[workspace]
members = [ "crates/as_command_derive",
    "crates/egui_mobius",
    "examples/*",
]
exclude = [
    # this example has its own workspace
    "examples/egui_crux_example"
]

resolver = "3"

[workspace.dependencies]
# egui mobius related crates
egui_mobius   = { path = "crates/egui_mobius" }
as_command_derive = { path = "crates/as_command_derive" }

# egui and eframe
egui = "0.31.0"
eframe = { version = "0.31.0", default-features = false }

# random number generation, useful for testing and examples
rand = "0.9.0"

# async support
tokio = "1.43.0"

# windowing
winit = "0.30.9"

# alternative to std::sync::mpsc
crossbeam-channel = "0.5.14"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
