#cargo-features = ["edition2024"]
[package]
name    = "simple_monitor_2"
version = "0.2.0"
edition = "2024"

[dependencies]
egui_mobius = { workspace = true }
as_command_derive = { workspace = true }
egui = { workspace = true }
eframe = { workspace = true, default-features = false, features = [
    "default_fonts",
    "glow",
    "wayland",
] }
rand = { workspace = true }


[[bin]]
name = "simple_monitor_2"
path = "src/main.rs"