[package]
name = "ui_refresh_events"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
egui_mobius = { path = "../../crates/egui_mobius" }
egui = { workspace = true }
eframe = {  workspace = true, features = ["glow"] }
log = "0.4"
env_logger = "0.9"

