[package]
name = "egui_mobius_examples"
version = "0.1.0"
edition = "2021"
publish = false
description = "Examples demonstrating egui_mobius features"

[lib]
path = "lib.rs"

[dependencies]
egui_mobius = { path = "../crates/egui_mobius" }
egui_mobius_widgets = { path = "../crates/egui_mobius_widgets" }
egui_mobius_reactive = { path = "../crates/egui_mobius_reactive" }
egui = "0.31"
eframe = "0.31"
tokio = { version = "1", features = ["full"] }
egui_plot = "0.31"
egui_taffy = "0.7.0"
rand = "0.8"
chrono = "0.4"
tracing = "0.1"
tracing-subscriber = "0.3"
env_logger = "0.11"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
lazy_static = "1.4"

[[example]]
name = "clock_async"
path = "clock_async/src/main.rs"

[[example]]
name = "dashboard"
path = "dashboard/src/main.rs"

[[example]]
name = "dashboard_async"
path = "dashboard_async/src/main.rs"

[[example]]
name = "reactive"
path = "reactive/src/main.rs"

[[example]]
name = "realtime_plot"
path = "realtime_plot/src/main.rs"

[[example]]
name = "subscriber"
path = "subscriber/src/main.rs"

[[example]]
name = "ui_refresh_events"
path = "ui_refresh_events/src/main.rs"


