[package]
name = "reactive"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
egui_mobius_reactive = { path = "../../crates/egui_mobius_reactive" }
egui_mobius = { path = "../../crates/egui_mobius" }
egui = { workspace = true }
eframe = { workspace = true, features = ["glow"] }

