[package]
name = "reactive_slider"
version = "0.1.0"
edition = "2021"

[dependencies]
egui_mobius_reactive = { path = "../../crates/egui_mobius_reactive", features = ["widgets"] }
egui = { workspace = true }
eframe = { workspace = true, features = ["glow"] }
