[package]
name = "logger_component"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
egui_mobius_components = { path = "../../crates/egui_mobius_components" }
egui = { workspace = true }
eframe = { workspace = true, features = ["glow"] }
