[package]
name = "release_tools"
version = "0.3.0-alpha.1"
edition = "2024"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
toml = "0.8"
serde = { version = "1.0", features = ["derive"] }
color-eyre = "0.6"
walkdir = "2.4"
semver = "1.0"
